### ISSUE TITLE
ProductVersion?

### ISSUE THREAD

**Issue by dusherwo57** [MariusWirtz-cubewise/TM1py#19]
Marius, I'm working with your get_view_content routine to create CSV output. Testing with 10.2.2 and with PA, I see that the dimension references come out differently:
10.2.2    '[actvsbud].[Actual]'
PA    '[actvsbud].['actvsbud'].[Actual]'
(ie the hierarchies show)
I could just count the fullstops, but I thought it worth proposing the inclusion of a object equivalent to the Rest call 
http://localhost:8010/api/v1/Configuration
which (inter alia) shows
"ProductVersion": "10.2.20700.43"
Users could then test the release and handle the output accordingly. I have looked through the latest version and couldn't spot this. What do you think?
FYI, I am hoping to be able to pass back some of the code I have been building, but I need clearance from the Directors and they are on holiday.

**Comment by dusherwo57** [comment]
Scratch the above - I've just found get_product_version :)

**Comment by MariusWirtz-cubewise** [comment]
Hi David,

regarding the inconsistency in the element unique names, the problem here lies in the TM1 REST API. 
TM1py shows the element unique names as it gets them from TM1 through the REST API.

Do you think we should work around it and make it consistent? e.g. always show the proper element unique name (including the hierarchy) even for TM1 10.2.2?
I mean Hierarchies do exist in TM1 10.2.2. Everything just always gets evaluated against the Hierarchy that has the same name as the dimension, right?

**Comment by dusherwo57** [comment]
I'd leave it as is - especially since I discovered that you had slipped in 
the version detection in the latest release!



David Usherwood | Associate 
InfoCat, Riverside House, 27/29 Vauxhall Grove, London, SW8 1SY
p: 020 7735 7711 |  f: 020 7735 8811 
www.infocat.co.uk 
This message is private and confidential. If you have received this message in 
error, please notify us and remove it from your system.
InfoCat Ltd. is a limited company registered in England. Registered number: 
2843261. Registered office: 27-29 Vauxhall Grove, London, SW8 1SY.

**Comment by dusherwo57** [comment]
Just seen the new release - looks good! I'll go through what I've done and 
see what needs changing. 
Do you have suggestions for how to migrate (not my code, the libraries)?
Also, samples has gone - do you intend to migrate this? It was very useful 
as a start point.



David Usherwood | Associate 
InfoCat, Riverside House, 27/29 Vauxhall Grove, London, SW8 1SY
p: 020 7735 7711 |  f: 020 7735 8811 
www.infocat.co.uk 
This message is private and confidential. If you have received this message in 
error, please notify us and remove it from your system.
InfoCat Ltd. is a limited company registered in England. Registered number: 
2843261. Registered office: 27-29 Vauxhall Grove, London, SW8 1SY.

From:   David Usherwood/InfoCat
To:     MariusWirtz-cubewise/TM1py 
<reply@reply.github.com>, 

Cc:     Author <author@noreply.github.com>, dusherwo57 
<davidu@infocat.co.uk>, MariusWirtz-cubewise/TM1py 
<TM1py@noreply.github.com>
Date:   18/08/2017 09:10
Subject:        Re: [MariusWirtz-cubewise/TM1py] ProductVersion? (#19)


I'd leave it as is - especially since I discovered that you had slipped in 
the version detection in the latest release!

**Comment by MariusWirtz-cubewise** [comment]
Sorry for causing you trouble with this migration. 

The TM1Service channels all the other Services now. 
So the users dont have to instantiate all kind of services explicitly. I think this is more elegant.

For migrating the samples I did four things
- Instead of instantiating the LoginService we can pass user, password and namespace as arguments to TM1Service or RESTService.
- replace 
`with TM1Service(address='localhost', port=8001, user='admin', password='apple', ssl=True) as tm1_rest: `
with 
`with TM1Service(address='localhost', port=8001, user='admin', password='apple', ssl=True) as tm1:`
- remove the instantiation of dimension_service etc.
- replace `dimension_service` by `tm1.dimensions` and `cube_service` by `tm1.cubes`, etc.

We also renamed the ThreadService to MonitoringService and the UserService to SecurityServices.
If you want to address them in the latest Release you could do it like this:

```
from TM1py.Services import TM1Service

with TM1Service(address='localhost', port=8001, user='admin', password='apple', ssl=True) as tm1:
    users = tm1.monitoring.get_active_users()
```

We are finishing the Refactoring and the Documentation these days. Once we are done everything will be backwards compatible.

We will push the the updated samples to a second repository (TM1py-samples).

Cheers,

Marius

**Comment by dusherwo57** [comment]
I wouldn't describe this as 'trouble' - as you say the changes are minor, 
and for the best anyway.
What I may need a hand with is adjusting to the changes in the tm1py 
install. I attach the notes I made originally:

My belief is that I should take the following steps to upgrade:
a       Remove from site-packages the folders:
Exceptions
Objects
Services
b       Install tm1py using pip
c       Adjust my scripts to take account of the changes
d       Test!
Does this seem right to you?


David Usherwood | Associate 
InfoCat, Riverside House, 27/29 Vauxhall Grove, London, SW8 1SY
p: 020 7735 7711 |  f: 020 7735 8811 
www.infocat.co.uk 
This message is private and confidential. If you have received this message in 
error, please notify us and remove it from your system.
InfoCat Ltd. is a limited company registered in England. Registered number: 
2843261. Registered office: 27-29 Vauxhall Grove, London, SW8 1SY.

**Comment by MariusWirtz-cubewise** [comment]
Yes. That looks good.
- remove the TM1py folder from site-packages (or if you have TM1py's subfolders in it, remove them instead).

I will upload the updated samples tomorrow to the new samples repository.
https://github.com/cubewise-code/TM1py-samples
